import Head from 'next/head'
import Navbar from '../components/Common/Navbar'
import Start from '../components/Start'
import Aktionen from '../components/Aktion/Aktionen'
import Footer from '../components/Common/Footer'
import MenuList from '../components/Menu/MenuList'


export default function Home() {
  return (
    
    <div>
      <Head>
        <title>Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      <Start />
      <Aktionen />
      <MenuList />
      <Footer />
      
    </div>
   
  )
}
